# Form implementation generated from reading ui file 'e:\Programacion\Programacion_Avanzada_2MV7\Practica6\Barrios_Mendez_JoseAlberto_Codigos\diseño.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(530, 650)
        MainWindow.setMinimumSize(QtCore.QSize(530, 650))
        MainWindow.setMaximumSize(QtCore.QSize(530, 650))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 530, 650))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("border-image: url(:/images/fondo.jpeg);\n"
"border-image: url(:/prefijoNuevo/fondo.jpeg);\n"
"border-radius: 20px;\n"
"\n"
"")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("e:\\Programacion\\Programacion_Avanzada_2MV7\\Practica6\\Barrios_Mendez_JoseAlberto_Codigos\\fondo.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(parent=self.widget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 530, 650))
        self.frame.setMinimumSize(QtCore.QSize(530, 650))
        self.frame.setMaximumSize(QtCore.QSize(530, 650))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setEnabled(True)
        self.frame_2.setMinimumSize(QtCore.QSize(524, 644))
        self.frame_2.setMaximumSize(QtCore.QSize(524, 644))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 20)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.arriba = QtWidgets.QFrame(parent=self.frame_2)
        self.arriba.setStyleSheet("QFrame {\n"
"    background-color: rgba(0, 0, 0, 100); \n"
"    border-radius:20px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius:20px;\n"
"}\n"
"\n"
"")
        self.arriba.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.arriba.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.arriba.setObjectName("arriba")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.arriba)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(299, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.minimizar = QtWidgets.QPushButton(parent=self.arriba)
        self.minimizar.setMinimumSize(QtCore.QSize(40, 40))
        self.minimizar.setStyleSheet("QPushButton:hover {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 251, 0, 255), stop:0.375 rgba(254, 255, 208, 117), stop:0.44 rgba(252, 250, 128, 80), stop:0.710227 rgba(255, 254, 162, 135), stop:0.727273 rgba(255, 255, 255, 255), stop:0.795455 rgba(236, 255, 132, 156), stop:1 rgba(255, 255, 255, 0));\n"
"    border-radius:20px;\n"
"}")
        self.minimizar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("e:\\Programacion\\Programacion_Avanzada_2MV7\\Practica6\\Barrios_Mendez_JoseAlberto_Codigos\\imagenes/menos.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.minimizar.setIcon(icon)
        self.minimizar.setIconSize(QtCore.QSize(25, 25))
        self.minimizar.setObjectName("minimizar")
        self.horizontalLayout.addWidget(self.minimizar)
        self.expandir = QtWidgets.QPushButton(parent=self.arriba)
        self.expandir.setMinimumSize(QtCore.QSize(40, 40))
        self.expandir.setStyleSheet("QPushButton:hover {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 255, 69, 255), stop:0.375 rgba(215, 255, 208, 117), stop:0.44 rgba(142, 252, 128, 80), stop:0.710227 rgba(173, 255, 162, 135), stop:0.727273 rgba(255, 255, 255, 255), stop:0.795455 rgba(132, 255, 165, 156), stop:1 rgba(255, 255, 255, 0));\n"
"    border-radius:20px;\n"
"}")
        self.expandir.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("e:\\Programacion\\Programacion_Avanzada_2MV7\\Practica6\\Barrios_Mendez_JoseAlberto_Codigos\\imagenes/max.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.expandir.setIcon(icon1)
        self.expandir.setIconSize(QtCore.QSize(25, 25))
        self.expandir.setObjectName("expandir")
        self.horizontalLayout.addWidget(self.expandir)
        self.reducir = QtWidgets.QPushButton(parent=self.arriba)
        self.reducir.setMinimumSize(QtCore.QSize(40, 40))
        self.reducir.setStyleSheet("QPushButton:hover {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(29, 0, 255, 255), stop:0.375 rgba(213, 208, 255, 117), stop:0.44 rgba(163, 128, 252, 80), stop:0.710227 rgba(162, 163, 255, 135), stop:0.727273 rgba(255, 255, 255, 255), stop:0.795455 rgba(132, 134, 255, 156), stop:1 rgba(255, 255, 255, 0));\n"
"    border-radius:20px;\n"
"}")
        self.reducir.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("e:\\Programacion\\Programacion_Avanzada_2MV7\\Practica6\\Barrios_Mendez_JoseAlberto_Codigos\\imagenes/min.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.reducir.setIcon(icon2)
        self.reducir.setIconSize(QtCore.QSize(25, 25))
        self.reducir.setObjectName("reducir")
        self.horizontalLayout.addWidget(self.reducir)
        self.cerrar = QtWidgets.QPushButton(parent=self.arriba)
        self.cerrar.setMinimumSize(QtCore.QSize(40, 40))
        self.cerrar.setStyleSheet("QPushButton:hover {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 0, 0, 255), stop:0.375 rgba(255, 208, 208, 117), stop:0.44 rgba(252, 128, 128, 80), stop:0.710227 rgba(255, 162, 162, 135), stop:0.727273 rgba(255, 255, 255, 255), stop:0.795455 rgba(255, 132, 132, 156), stop:1 rgba(255, 255, 255, 0));\n"
"    border-radius:20px;\n"
"}")
        self.cerrar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("e:\\Programacion\\Programacion_Avanzada_2MV7\\Practica6\\Barrios_Mendez_JoseAlberto_Codigos\\imagenes/tache.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.cerrar.setIcon(icon3)
        self.cerrar.setIconSize(QtCore.QSize(25, 25))
        self.cerrar.setObjectName("cerrar")
        self.horizontalLayout.addWidget(self.cerrar)
        self.verticalLayout_3.addWidget(self.arriba)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_4)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 504, 535))
        self.stackedWidget.setMinimumSize(QtCore.QSize(504, 535))
        self.stackedWidget.setMaximumSize(QtCore.QSize(504, 535))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setProperty("fonfoo", QtGui.QPixmap("e:\\Programacion\\Programacion_Avanzada_2MV7\\Practica6\\Barrios_Mendez_JoseAlberto_Codigos\\fondo.jpeg"))
        self.stackedWidget.setObjectName("stackedWidget")
        self.seleccion = QtWidgets.QWidget()
        self.seleccion.setStyleSheet("QWidget {\n"
"    background-color: rgba(0, 0, 0, 100); \n"
"    border-radius:20px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: 87 20pt \"Txt\";\n"
"    background-color: #000000ff;\n"
"    border-radius: 5px;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: black;\n"
"}")
        self.seleccion.setObjectName("seleccion")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.seleccion)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_17 = QtWidgets.QLabel(parent=self.seleccion)
        self.label_17.setMinimumSize(QtCore.QSize(480, 60))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 480))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        self.label_17.setFont(font)
        self.label_17.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.label_17.setStyleSheet("font: 700 35pt \"MS Sans Serif\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"")
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_8.addWidget(self.label_17)
        spacerItem1 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_8.addItem(spacerItem1)
        self.label_16 = QtWidgets.QLabel(parent=self.seleccion)
        self.label_16.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 156, 156);\n"
"background-color: #000000ff;\n"
"\n"
"    ")
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_8.addWidget(self.label_16)
        spacerItem2 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_8.addItem(spacerItem2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.jugadores1 = QtWidgets.QPushButton(parent=self.seleccion)
        self.jugadores1.setMinimumSize(QtCore.QSize(320, 0))
        self.jugadores1.setMaximumSize(QtCore.QSize(320, 16777215))
        self.jugadores1.setStyleSheet("color: rgb(165, 210, 255);")
        self.jugadores1.setObjectName("jugadores1")
        self.verticalLayout_4.addWidget(self.jugadores1)
        self.extremo = QtWidgets.QPushButton(parent=self.seleccion)
        self.extremo.setMinimumSize(QtCore.QSize(320, 0))
        self.extremo.setMaximumSize(QtCore.QSize(320, 16777215))
        self.extremo.setStyleSheet("color: rgb(188, 255, 187);")
        self.extremo.setObjectName("extremo")
        self.verticalLayout_4.addWidget(self.extremo)
        self.exit = QtWidgets.QPushButton(parent=self.seleccion)
        self.exit.setMinimumSize(QtCore.QSize(320, 0))
        self.exit.setMaximumSize(QtCore.QSize(320, 16777215))
        self.exit.setStyleSheet("color: rgb(255, 255, 175)")
        self.exit.setObjectName("exit")
        self.verticalLayout_4.addWidget(self.exit)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        spacerItem5 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem5)
        self.stackedWidget.addWidget(self.seleccion)
        self.simon = QtWidgets.QWidget()
        self.simon.setStyleSheet("QWidget {\n"
"    background-color: rgba(0, 0, 0, 100); \n"
"    border-radius:20px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: 87 20pt \"Txt\";\n"
"    background-color: #000000ff;\n"
"    border-radius: 5px;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: black;\n"
"}\n"
"")
        self.simon.setObjectName("simon")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.simon)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_13 = QtWidgets.QLabel(parent=self.simon)
        self.label_13.setMinimumSize(QtCore.QSize(480, 60))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.label_13.setStyleSheet("font: 700 35pt \"MS Sans Serif\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"")
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        spacerItem6 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem6)
        self.label_14 = QtWidgets.QLabel(parent=self.simon)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_14.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 156, 156);\n"
"background-color: #000000ff;\n"
"\n"
"    ")
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_7.addWidget(self.label_14)
        self.in_nombre1 = QtWidgets.QTextEdit(parent=self.simon)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_nombre1.sizePolicy().hasHeightForWidth())
        self.in_nombre1.setSizePolicy(sizePolicy)
        self.in_nombre1.setMinimumSize(QtCore.QSize(0, 34))
        self.in_nombre1.setMaximumSize(QtCore.QSize(16777215, 35))
        self.in_nombre1.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"border: none;\n"
"border-bottom: 1px solid white;")
        self.in_nombre1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.in_nombre1.setObjectName("in_nombre1")
        self.verticalLayout_7.addWidget(self.in_nombre1)
        self.label_15 = QtWidgets.QLabel(parent=self.simon)
        self.label_15.setMinimumSize(QtCore.QSize(0, 34))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_15.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 156, 156);\n"
"background-color: #000000ff;")
        self.label_15.setText("")
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_7.addWidget(self.label_15)
        spacerItem7 = QtWidgets.QSpacerItem(20, 59, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.play_5 = QtWidgets.QPushButton(parent=self.simon)
        self.play_5.setMinimumSize(QtCore.QSize(320, 0))
        self.play_5.setMaximumSize(QtCore.QSize(320, 16777215))
        self.play_5.setStyleSheet("color: rgb(165, 210, 255);")
        self.play_5.setObjectName("play_5")
        self.verticalLayout_6.addWidget(self.play_5)
        self.menu = QtWidgets.QPushButton(parent=self.simon)
        self.menu.setMinimumSize(QtCore.QSize(320, 0))
        self.menu.setMaximumSize(QtCore.QSize(320, 16777215))
        self.menu.setStyleSheet("color: rgb(255, 255, 175)")
        self.menu.setObjectName("menu")
        self.verticalLayout_6.addWidget(self.menu)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        spacerItem10 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem10)
        self.stackedWidget.addWidget(self.simon)
        self.jugadores = QtWidgets.QWidget()
        self.jugadores.setStyleSheet("QWidget {\n"
"    background-color: rgba(0, 0, 0, 100); \n"
"    border-radius:20px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: 87 20pt \"Txt\";\n"
"    background-color: #000000ff;\n"
"    border-radius: 5px;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: black;\n"
"}")
        self.jugadores.setObjectName("jugadores")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.jugadores)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_19 = QtWidgets.QLabel(parent=self.jugadores)
        self.label_19.setMinimumSize(QtCore.QSize(480, 60))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        self.label_19.setFont(font)
        self.label_19.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.label_19.setStyleSheet("font: 700 35pt \"MS Sans Serif\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"")
        self.label_19.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_10.addWidget(self.label_19)
        spacerItem11 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_10.addItem(spacerItem11)
        self.label_18 = QtWidgets.QLabel(parent=self.jugadores)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_18.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 156, 156);\n"
"background-color: #000000ff;\n"
"\n"
"    ")
        self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_10.addWidget(self.label_18)
        spacerItem12 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_10.addItem(spacerItem12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem13)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.jugadores2 = QtWidgets.QPushButton(parent=self.jugadores)
        self.jugadores2.setMinimumSize(QtCore.QSize(320, 0))
        self.jugadores2.setMaximumSize(QtCore.QSize(320, 16777215))
        self.jugadores2.setStyleSheet("color: rgb(165, 210, 255);")
        self.jugadores2.setObjectName("jugadores2")
        self.verticalLayout_9.addWidget(self.jugadores2)
        self.jugadores3 = QtWidgets.QPushButton(parent=self.jugadores)
        self.jugadores3.setMinimumSize(QtCore.QSize(320, 0))
        self.jugadores3.setMaximumSize(QtCore.QSize(320, 16777215))
        self.jugadores3.setStyleSheet("color: rgb(188, 255, 187);")
        self.jugadores3.setObjectName("jugadores3")
        self.verticalLayout_9.addWidget(self.jugadores3)
        self.jugadores4 = QtWidgets.QPushButton(parent=self.jugadores)
        self.jugadores4.setMinimumSize(QtCore.QSize(320, 0))
        self.jugadores4.setMaximumSize(QtCore.QSize(320, 16777215))
        self.jugadores4.setStyleSheet("color: rgb(255, 255, 175)")
        self.jugadores4.setObjectName("jugadores4")
        self.verticalLayout_9.addWidget(self.jugadores4)
        self.jugadores5 = QtWidgets.QPushButton(parent=self.jugadores)
        self.jugadores5.setStyleSheet("color: rgb(255, 156, 156);\n"
"border-radius: 5px;\n"
"border: 1px solid white;")
        self.jugadores5.setObjectName("jugadores5")
        self.verticalLayout_9.addWidget(self.jugadores5)
        self.horizontalLayout_13.addLayout(self.verticalLayout_9)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem14)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        spacerItem15 = QtWidgets.QSpacerItem(20, 106, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_10.addItem(spacerItem15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem16)
        self.menu_multi = QtWidgets.QPushButton(parent=self.jugadores)
        self.menu_multi.setMinimumSize(QtCore.QSize(200, 0))
        self.menu_multi.setMaximumSize(QtCore.QSize(200, 16777215))
        self.menu_multi.setStyleSheet("color: rgb(165, 210, 255);\n"
"border-radius: 5px;\n"
"border: 1px solid white;")
        self.menu_multi.setObjectName("menu_multi")
        self.horizontalLayout_14.addWidget(self.menu_multi)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.stackedWidget.addWidget(self.jugadores)
        self.un_jugador = QtWidgets.QWidget()
        self.un_jugador.setStyleSheet("QWidget {\n"
"    background-color: rgba(0, 0, 0, 100); \n"
"    border-radius:20px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: 87 20pt \"Txt\";\n"
"    background-color: #000000ff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: black;\n"
"}")
        self.un_jugador.setObjectName("un_jugador")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.un_jugador)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem17)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(parent=self.un_jugador)
        self.label_6.setStyleSheet("font: 700 35pt \"MS Sans Serif\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        spacerItem18 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem18)
        self.label_8 = QtWidgets.QLabel(parent=self.un_jugador)
        self.label_8.setStyleSheet("font: 700 35pt \"MS Sans Serif\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_6)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem19)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem20)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(parent=self.un_jugador)
        self.label_7.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 156, 156);\n"
"background-color: #000000ff;")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        spacerItem21 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem21)
        self.label_9 = QtWidgets.QLabel(parent=self.un_jugador)
        self.label_9.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(165, 210, 255);\n"
"background-color: #000000ff;\n"
"\n"
"    ")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_5)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem22)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_5.addItem(spacerItem23)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem24)
        self.iniciar_1jugador = QtWidgets.QPushButton(parent=self.un_jugador)
        self.iniciar_1jugador.setMaximumSize(QtCore.QSize(70, 70))
        self.iniciar_1jugador.setStyleSheet("QPushButton:hover {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 255, 69, 255), stop:0.375 rgba(215, 255, 208, 117), stop:0.44 rgba(142, 252, 128, 80), stop:0.710227 rgba(173, 255, 162, 135), stop:0.727273 rgba(255, 255, 255, 255), stop:0.795455 rgba(132, 255, 165, 156), stop:1 rgba(255, 255, 255, 0));\n"
"    border-radius:20px;\n"
"}")
        self.iniciar_1jugador.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("e:\\Programacion\\Programacion_Avanzada_2MV7\\Practica6\\Barrios_Mendez_JoseAlberto_Codigos\\imagenes/play.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.iniciar_1jugador.setIcon(icon4)
        self.iniciar_1jugador.setIconSize(QtCore.QSize(70, 70))
        self.iniciar_1jugador.setObjectName("iniciar_1jugador")
        self.horizontalLayout_4.addWidget(self.iniciar_1jugador)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem25)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_5.addItem(spacerItem26)
        self.label_12 = QtWidgets.QLabel(parent=self.un_jugador)
        self.label_12.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 255, 175);\n"
"background-color: #000000ff;\n"
"\n"
"    ")
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem27)
        self.lento_2 = QtWidgets.QPushButton(parent=self.un_jugador)
        self.lento_2.setMinimumSize(QtCore.QSize(130, 0))
        self.lento_2.setStyleSheet("color: rgb(255, 156, 156);\n"
"border-radius: 5px;\n"
"border: 1px solid white;")
        self.lento_2.setObjectName("lento_2")
        self.horizontalLayout_7.addWidget(self.lento_2)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem28)
        self.medio_2 = QtWidgets.QPushButton(parent=self.un_jugador)
        self.medio_2.setMinimumSize(QtCore.QSize(130, 0))
        self.medio_2.setStyleSheet("color: rgb(165, 210, 255);\n"
"border-radius: 5px;\n"
"border: 1px solid white;")
        self.medio_2.setObjectName("medio_2")
        self.horizontalLayout_7.addWidget(self.medio_2)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem29)
        self.rapido_2 = QtWidgets.QPushButton(parent=self.un_jugador)
        self.rapido_2.setMinimumSize(QtCore.QSize(130, 0))
        self.rapido_2.setStyleSheet("color: rgb(188, 255, 187);\n"
"border-radius: 5px;\n"
"border: 1px solid white;")
        self.rapido_2.setObjectName("rapido_2")
        self.horizontalLayout_7.addWidget(self.rapido_2)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem30)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        spacerItem31 = QtWidgets.QSpacerItem(20, 64, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem31)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem32)
        self.menu_puntaje = QtWidgets.QPushButton(parent=self.un_jugador)
        self.menu_puntaje.setMinimumSize(QtCore.QSize(200, 0))
        self.menu_puntaje.setMaximumSize(QtCore.QSize(200, 16777215))
        self.menu_puntaje.setStyleSheet("color: rgb(255, 255, 175);\n"
"border-radius: 5px;\n"
"border: 1px solid white;")
        self.menu_puntaje.setObjectName("menu_puntaje")
        self.horizontalLayout_10.addWidget(self.menu_puntaje)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.stackedWidget.addWidget(self.un_jugador)
        self.dos = QtWidgets.QWidget()
        self.dos.setStyleSheet("QWidget {\n"
"    background-color: rgba(0, 0, 0, 100); \n"
"    border-radius:20px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: 87 20pt \"Txt\";\n"
"    background-color: #000000ff;\n"
"    border-radius: 5px;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: black;\n"
"}")
        self.dos.setObjectName("dos")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.dos)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_21 = QtWidgets.QLabel(parent=self.dos)
        self.label_21.setMinimumSize(QtCore.QSize(480, 60))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        self.label_21.setFont(font)
        self.label_21.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.label_21.setStyleSheet("font: 700 35pt \"MS Sans Serif\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"")
        self.label_21.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_12.addWidget(self.label_21)
        spacerItem33 = QtWidgets.QSpacerItem(20, 46, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_12.addItem(spacerItem33)
        self.label_20 = QtWidgets.QLabel(parent=self.dos)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_20.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 156, 156);\n"
"background-color: #000000ff;\n"
"\n"
"    ")
        self.label_20.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_12.addWidget(self.label_20)
        self.in_nombre = QtWidgets.QTextEdit(parent=self.dos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_nombre.sizePolicy().hasHeightForWidth())
        self.in_nombre.setSizePolicy(sizePolicy)
        self.in_nombre.setMinimumSize(QtCore.QSize(0, 34))
        self.in_nombre.setMaximumSize(QtCore.QSize(16777215, 35))
        self.in_nombre.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"border: none;\n"
"border-bottom: 1px solid white;")
        self.in_nombre.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.in_nombre.setObjectName("in_nombre")
        self.verticalLayout_12.addWidget(self.in_nombre)
        self.in_nombre_2 = QtWidgets.QTextEdit(parent=self.dos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_nombre_2.sizePolicy().hasHeightForWidth())
        self.in_nombre_2.setSizePolicy(sizePolicy)
        self.in_nombre_2.setMinimumSize(QtCore.QSize(0, 34))
        self.in_nombre_2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.in_nombre_2.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"border: none;\n"
"border-bottom: 1px solid white;")
        self.in_nombre_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.in_nombre_2.setObjectName("in_nombre_2")
        self.verticalLayout_12.addWidget(self.in_nombre_2)
        self.label_22 = QtWidgets.QLabel(parent=self.dos)
        self.label_22.setMinimumSize(QtCore.QSize(0, 34))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_22.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 156, 156);\n"
"background-color: #000000ff;")
        self.label_22.setText("")
        self.label_22.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_12.addWidget(self.label_22)
        spacerItem34 = QtWidgets.QSpacerItem(20, 46, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_12.addItem(spacerItem34)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem35)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.play_4 = QtWidgets.QPushButton(parent=self.dos)
        self.play_4.setMinimumSize(QtCore.QSize(320, 0))
        self.play_4.setMaximumSize(QtCore.QSize(320, 16777215))
        self.play_4.setStyleSheet("color: rgb(165, 210, 255);")
        self.play_4.setObjectName("play_4")
        self.verticalLayout_11.addWidget(self.play_4)
        self.menu_2p = QtWidgets.QPushButton(parent=self.dos)
        self.menu_2p.setMinimumSize(QtCore.QSize(320, 0))
        self.menu_2p.setMaximumSize(QtCore.QSize(320, 16777215))
        self.menu_2p.setStyleSheet("color: rgb(255, 255, 175)")
        self.menu_2p.setObjectName("menu_2p")
        self.verticalLayout_11.addWidget(self.menu_2p)
        self.horizontalLayout_15.addLayout(self.verticalLayout_11)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem36)
        self.verticalLayout_12.addLayout(self.horizontalLayout_15)
        spacerItem37 = QtWidgets.QSpacerItem(20, 46, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_12.addItem(spacerItem37)
        self.stackedWidget.addWidget(self.dos)
        self.tres = QtWidgets.QWidget()
        self.tres.setStyleSheet("QWidget {\n"
"    background-color: rgba(0, 0, 0, 100); \n"
"    border-radius:20px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: 87 20pt \"Txt\";\n"
"    background-color: #000000ff;\n"
"    border-radius: 5px;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: black;\n"
"}")
        self.tres.setObjectName("tres")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tres)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_24 = QtWidgets.QLabel(parent=self.tres)
        self.label_24.setMinimumSize(QtCore.QSize(480, 60))
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        self.label_24.setFont(font)
        self.label_24.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.label_24.setStyleSheet("font: 700 35pt \"MS Sans Serif\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"")
        self.label_24.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_16.addWidget(self.label_24)
        spacerItem38 = QtWidgets.QSpacerItem(20, 33, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_16.addItem(spacerItem38)
        self.label_23 = QtWidgets.QLabel(parent=self.tres)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_23.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 156, 156);\n"
"background-color: #000000ff;\n"
"\n"
"    ")
        self.label_23.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_16.addWidget(self.label_23)
        self.in_nombre_3 = QtWidgets.QTextEdit(parent=self.tres)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_nombre_3.sizePolicy().hasHeightForWidth())
        self.in_nombre_3.setSizePolicy(sizePolicy)
        self.in_nombre_3.setMinimumSize(QtCore.QSize(0, 34))
        self.in_nombre_3.setMaximumSize(QtCore.QSize(16777215, 35))
        self.in_nombre_3.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"border: none;\n"
"border-bottom: 1px solid white;")
        self.in_nombre_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.in_nombre_3.setObjectName("in_nombre_3")
        self.verticalLayout_16.addWidget(self.in_nombre_3)
        self.in_nombre_4 = QtWidgets.QTextEdit(parent=self.tres)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_nombre_4.sizePolicy().hasHeightForWidth())
        self.in_nombre_4.setSizePolicy(sizePolicy)
        self.in_nombre_4.setMinimumSize(QtCore.QSize(0, 34))
        self.in_nombre_4.setMaximumSize(QtCore.QSize(16777215, 35))
        self.in_nombre_4.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"border: none;\n"
"border-bottom: 1px solid white;")
        self.in_nombre_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.in_nombre_4.setObjectName("in_nombre_4")
        self.verticalLayout_16.addWidget(self.in_nombre_4)
        self.in_nombre_5 = QtWidgets.QTextEdit(parent=self.tres)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_nombre_5.sizePolicy().hasHeightForWidth())
        self.in_nombre_5.setSizePolicy(sizePolicy)
        self.in_nombre_5.setMinimumSize(QtCore.QSize(0, 34))
        self.in_nombre_5.setMaximumSize(QtCore.QSize(16777215, 35))
        self.in_nombre_5.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"border: none;\n"
"border-bottom: 1px solid white;")
        self.in_nombre_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.in_nombre_5.setObjectName("in_nombre_5")
        self.verticalLayout_16.addWidget(self.in_nombre_5)
        self.label_25 = QtWidgets.QLabel(parent=self.tres)
        self.label_25.setMinimumSize(QtCore.QSize(0, 34))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_25.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 156, 156);\n"
"background-color: #000000ff;")
        self.label_25.setText("")
        self.label_25.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_16.addWidget(self.label_25)
        spacerItem39 = QtWidgets.QSpacerItem(20, 34, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_16.addItem(spacerItem39)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem40)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.play_3 = QtWidgets.QPushButton(parent=self.tres)
        self.play_3.setMinimumSize(QtCore.QSize(320, 0))
        self.play_3.setMaximumSize(QtCore.QSize(320, 16777215))
        self.play_3.setStyleSheet("color: rgb(165, 210, 255);")
        self.play_3.setObjectName("play_3")
        self.verticalLayout_13.addWidget(self.play_3)
        self.menu_3p = QtWidgets.QPushButton(parent=self.tres)
        self.menu_3p.setMinimumSize(QtCore.QSize(320, 0))
        self.menu_3p.setMaximumSize(QtCore.QSize(320, 16777215))
        self.menu_3p.setStyleSheet("color: rgb(255, 255, 175)")
        self.menu_3p.setObjectName("menu_3p")
        self.verticalLayout_13.addWidget(self.menu_3p)
        self.horizontalLayout_16.addLayout(self.verticalLayout_13)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem41)
        self.verticalLayout_16.addLayout(self.horizontalLayout_16)
        spacerItem42 = QtWidgets.QSpacerItem(20, 33, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_16.addItem(spacerItem42)
        self.stackedWidget.addWidget(self.tres)
        self.cuatro = QtWidgets.QWidget()
        self.cuatro.setStyleSheet("QWidget {\n"
"    background-color: rgba(0, 0, 0, 100); \n"
"    border-radius:20px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: 87 20pt \"Txt\";\n"
"    background-color: #000000ff;\n"
"    border-radius: 5px;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: black;\n"
"}")
        self.cuatro.setObjectName("cuatro")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.cuatro)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_27 = QtWidgets.QLabel(parent=self.cuatro)
        self.label_27.setMinimumSize(QtCore.QSize(480, 60))
        self.label_27.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        self.label_27.setFont(font)
        self.label_27.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.label_27.setStyleSheet("font: 700 35pt \"MS Sans Serif\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"")
        self.label_27.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_15.addWidget(self.label_27)
        spacerItem43 = QtWidgets.QSpacerItem(20, 19, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_15.addItem(spacerItem43)
        self.label_26 = QtWidgets.QLabel(parent=self.cuatro)
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_26.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 156, 156);\n"
"background-color: #000000ff;\n"
"\n"
"    ")
        self.label_26.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_15.addWidget(self.label_26)
        self.in_nombre_6 = QtWidgets.QTextEdit(parent=self.cuatro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_nombre_6.sizePolicy().hasHeightForWidth())
        self.in_nombre_6.setSizePolicy(sizePolicy)
        self.in_nombre_6.setMinimumSize(QtCore.QSize(0, 34))
        self.in_nombre_6.setMaximumSize(QtCore.QSize(16777215, 35))
        self.in_nombre_6.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"border: none;\n"
"border-bottom: 1px solid white;")
        self.in_nombre_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.in_nombre_6.setObjectName("in_nombre_6")
        self.verticalLayout_15.addWidget(self.in_nombre_6)
        self.in_nombre_7 = QtWidgets.QTextEdit(parent=self.cuatro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_nombre_7.sizePolicy().hasHeightForWidth())
        self.in_nombre_7.setSizePolicy(sizePolicy)
        self.in_nombre_7.setMinimumSize(QtCore.QSize(0, 34))
        self.in_nombre_7.setMaximumSize(QtCore.QSize(16777215, 35))
        self.in_nombre_7.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"border: none;\n"
"border-bottom: 1px solid white;")
        self.in_nombre_7.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.in_nombre_7.setObjectName("in_nombre_7")
        self.verticalLayout_15.addWidget(self.in_nombre_7)
        self.in_nombre_8 = QtWidgets.QTextEdit(parent=self.cuatro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_nombre_8.sizePolicy().hasHeightForWidth())
        self.in_nombre_8.setSizePolicy(sizePolicy)
        self.in_nombre_8.setMinimumSize(QtCore.QSize(0, 34))
        self.in_nombre_8.setMaximumSize(QtCore.QSize(16777215, 35))
        self.in_nombre_8.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"border: none;\n"
"border-bottom: 1px solid white;")
        self.in_nombre_8.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.in_nombre_8.setObjectName("in_nombre_8")
        self.verticalLayout_15.addWidget(self.in_nombre_8)
        self.in_nombre_9 = QtWidgets.QTextEdit(parent=self.cuatro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_nombre_9.sizePolicy().hasHeightForWidth())
        self.in_nombre_9.setSizePolicy(sizePolicy)
        self.in_nombre_9.setMinimumSize(QtCore.QSize(0, 34))
        self.in_nombre_9.setMaximumSize(QtCore.QSize(16777215, 35))
        self.in_nombre_9.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"border: none;\n"
"border-bottom: 1px solid white;")
        self.in_nombre_9.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.in_nombre_9.setObjectName("in_nombre_9")
        self.verticalLayout_15.addWidget(self.in_nombre_9)
        self.label_28 = QtWidgets.QLabel(parent=self.cuatro)
        self.label_28.setMinimumSize(QtCore.QSize(0, 34))
        self.label_28.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_28.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 156, 156);\n"
"background-color: #000000ff;")
        self.label_28.setText("")
        self.label_28.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_15.addWidget(self.label_28)
        spacerItem44 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_15.addItem(spacerItem44)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem45 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem45)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.play_2 = QtWidgets.QPushButton(parent=self.cuatro)
        self.play_2.setMinimumSize(QtCore.QSize(320, 0))
        self.play_2.setMaximumSize(QtCore.QSize(320, 16777215))
        self.play_2.setStyleSheet("color: rgb(165, 210, 255);")
        self.play_2.setObjectName("play_2")
        self.verticalLayout_14.addWidget(self.play_2)
        self.menu_4p = QtWidgets.QPushButton(parent=self.cuatro)
        self.menu_4p.setMinimumSize(QtCore.QSize(320, 0))
        self.menu_4p.setMaximumSize(QtCore.QSize(320, 16777215))
        self.menu_4p.setStyleSheet("color: rgb(255, 255, 175)")
        self.menu_4p.setObjectName("menu_4p")
        self.verticalLayout_14.addWidget(self.menu_4p)
        self.horizontalLayout_17.addLayout(self.verticalLayout_14)
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem46)
        self.verticalLayout_15.addLayout(self.horizontalLayout_17)
        spacerItem47 = QtWidgets.QSpacerItem(20, 19, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_15.addItem(spacerItem47)
        self.stackedWidget.addWidget(self.cuatro)
        self.cinco = QtWidgets.QWidget()
        self.cinco.setStyleSheet("QWidget {\n"
"    background-color: rgba(0, 0, 0, 100); \n"
"    border-radius:20px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: 87 20pt \"Txt\";\n"
"    background-color: #000000ff;\n"
"    border-radius: 5px;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: black;\n"
"}")
        self.cinco.setObjectName("cinco")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.cinco)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_34 = QtWidgets.QLabel(parent=self.cinco)
        self.label_34.setMinimumSize(QtCore.QSize(480, 60))
        self.label_34.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        self.label_34.setFont(font)
        self.label_34.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.label_34.setStyleSheet("font: 700 35pt \"MS Sans Serif\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"")
        self.label_34.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_20.addWidget(self.label_34)
        spacerItem48 = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_20.addItem(spacerItem48)
        self.label_4 = QtWidgets.QLabel(parent=self.cinco)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_4.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 156, 156);\n"
"background-color: #000000ff;\n"
"\n"
"    ")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_20.addWidget(self.label_4)
        self.in_nombre_10 = QtWidgets.QTextEdit(parent=self.cinco)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_nombre_10.sizePolicy().hasHeightForWidth())
        self.in_nombre_10.setSizePolicy(sizePolicy)
        self.in_nombre_10.setMinimumSize(QtCore.QSize(0, 34))
        self.in_nombre_10.setMaximumSize(QtCore.QSize(16777215, 35))
        self.in_nombre_10.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"border: none;\n"
"border-bottom: 1px solid white;")
        self.in_nombre_10.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.in_nombre_10.setObjectName("in_nombre_10")
        self.verticalLayout_20.addWidget(self.in_nombre_10)
        self.in_nombre_11 = QtWidgets.QTextEdit(parent=self.cinco)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_nombre_11.sizePolicy().hasHeightForWidth())
        self.in_nombre_11.setSizePolicy(sizePolicy)
        self.in_nombre_11.setMinimumSize(QtCore.QSize(0, 34))
        self.in_nombre_11.setMaximumSize(QtCore.QSize(16777215, 35))
        self.in_nombre_11.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"border: none;\n"
"border-bottom: 1px solid white;")
        self.in_nombre_11.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.in_nombre_11.setObjectName("in_nombre_11")
        self.verticalLayout_20.addWidget(self.in_nombre_11)
        self.in_nombre_12 = QtWidgets.QTextEdit(parent=self.cinco)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_nombre_12.sizePolicy().hasHeightForWidth())
        self.in_nombre_12.setSizePolicy(sizePolicy)
        self.in_nombre_12.setMinimumSize(QtCore.QSize(0, 34))
        self.in_nombre_12.setMaximumSize(QtCore.QSize(16777215, 35))
        self.in_nombre_12.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"border: none;\n"
"border-bottom: 1px solid white;")
        self.in_nombre_12.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.in_nombre_12.setObjectName("in_nombre_12")
        self.verticalLayout_20.addWidget(self.in_nombre_12)
        self.in_nombre_13 = QtWidgets.QTextEdit(parent=self.cinco)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_nombre_13.sizePolicy().hasHeightForWidth())
        self.in_nombre_13.setSizePolicy(sizePolicy)
        self.in_nombre_13.setMinimumSize(QtCore.QSize(0, 34))
        self.in_nombre_13.setMaximumSize(QtCore.QSize(16777215, 35))
        self.in_nombre_13.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"border: none;\n"
"border-bottom: 1px solid white;")
        self.in_nombre_13.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.in_nombre_13.setObjectName("in_nombre_13")
        self.verticalLayout_20.addWidget(self.in_nombre_13)
        self.in_nombre_14 = QtWidgets.QTextEdit(parent=self.cinco)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_nombre_14.sizePolicy().hasHeightForWidth())
        self.in_nombre_14.setSizePolicy(sizePolicy)
        self.in_nombre_14.setMinimumSize(QtCore.QSize(0, 34))
        self.in_nombre_14.setMaximumSize(QtCore.QSize(16777215, 35))
        self.in_nombre_14.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"border: none;\n"
"border-bottom: 1px solid white;")
        self.in_nombre_14.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.in_nombre_14.setObjectName("in_nombre_14")
        self.verticalLayout_20.addWidget(self.in_nombre_14)
        self.label_35 = QtWidgets.QLabel(parent=self.cinco)
        self.label_35.setMinimumSize(QtCore.QSize(0, 34))
        self.label_35.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_35.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 156, 156);\n"
"background-color: #000000ff;")
        self.label_35.setText("")
        self.label_35.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_20.addWidget(self.label_35)
        spacerItem49 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_20.addItem(spacerItem49)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem50 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem50)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.play_1 = QtWidgets.QPushButton(parent=self.cinco)
        self.play_1.setMinimumSize(QtCore.QSize(320, 0))
        self.play_1.setMaximumSize(QtCore.QSize(320, 16777215))
        self.play_1.setStyleSheet("color: rgb(165, 210, 255);")
        self.play_1.setObjectName("play_1")
        self.verticalLayout_19.addWidget(self.play_1)
        self.menu_5p = QtWidgets.QPushButton(parent=self.cinco)
        self.menu_5p.setMinimumSize(QtCore.QSize(320, 0))
        self.menu_5p.setMaximumSize(QtCore.QSize(320, 16777215))
        self.menu_5p.setStyleSheet("color: rgb(255, 255, 175)")
        self.menu_5p.setObjectName("menu_5p")
        self.verticalLayout_19.addWidget(self.menu_5p)
        self.horizontalLayout_22.addLayout(self.verticalLayout_19)
        spacerItem51 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem51)
        self.verticalLayout_20.addLayout(self.horizontalLayout_22)
        spacerItem52 = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_20.addItem(spacerItem52)
        self.stackedWidget.addWidget(self.cinco)
        self.multijugador = QtWidgets.QWidget()
        self.multijugador.setStyleSheet("QWidget {\n"
"    background-color: rgba(0, 0, 0, 100); \n"
"    border-radius:20px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: 87 20pt \"Txt\";\n"
"    background-color: #000000ff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: black;\n"
"}")
        self.multijugador.setObjectName("multijugador")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.multijugador)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_nombre_jugador = QtWidgets.QLabel(parent=self.multijugador)
        self.label_nombre_jugador.setStyleSheet("font: 700 35pt \"MS Sans Serif\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"\n"
"")
        self.label_nombre_jugador.setText("")
        self.label_nombre_jugador.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_nombre_jugador.setObjectName("label_nombre_jugador")
        self.verticalLayout_18.addWidget(self.label_nombre_jugador)
        spacerItem53 = QtWidgets.QSpacerItem(20, 19, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_18.addItem(spacerItem53)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem54 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem54)
        self.puntaje_actual = QtWidgets.QLabel(parent=self.multijugador)
        self.puntaje_actual.setStyleSheet("font: 700 35pt \"MS Sans Serif\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"")
        self.puntaje_actual.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.puntaje_actual.setObjectName("puntaje_actual")
        self.horizontalLayout_2.addWidget(self.puntaje_actual)
        spacerItem55 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem55)
        self.label_30 = QtWidgets.QLabel(parent=self.multijugador)
        self.label_30.setStyleSheet("font: 700 35pt \"MS Sans Serif\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"")
        self.label_30.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_2.addWidget(self.label_30)
        spacerItem56 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem56)
        self.verticalLayout_18.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem57 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem57)
        self.label_10 = QtWidgets.QLabel(parent=self.multijugador)
        self.label_10.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 156, 156);\n"
"background-color: #000000ff;")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        spacerItem58 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem58)
        self.label_32 = QtWidgets.QLabel(parent=self.multijugador)
        self.label_32.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(165, 210, 255);\n"
"background-color: #000000ff;\n"
"\n"
"    ")
        self.label_32.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_3.addWidget(self.label_32)
        spacerItem59 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem59)
        self.verticalLayout_18.addLayout(self.horizontalLayout_3)
        spacerItem60 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_18.addItem(spacerItem60)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem61 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem61)
        self.iniciar_multijugador = QtWidgets.QPushButton(parent=self.multijugador)
        self.iniciar_multijugador.setMaximumSize(QtCore.QSize(70, 70))
        self.iniciar_multijugador.setStyleSheet("QPushButton:hover {\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 255, 69, 255), stop:0.375 rgba(215, 255, 208, 117), stop:0.44 rgba(142, 252, 128, 80), stop:0.710227 rgba(173, 255, 162, 135), stop:0.727273 rgba(255, 255, 255, 255), stop:0.795455 rgba(132, 255, 165, 156), stop:1 rgba(255, 255, 255, 0));\n"
"    border-radius:20px;\n"
"}")
        self.iniciar_multijugador.setText("")
        self.iniciar_multijugador.setIcon(icon4)
        self.iniciar_multijugador.setIconSize(QtCore.QSize(70, 70))
        self.iniciar_multijugador.setObjectName("iniciar_multijugador")
        self.horizontalLayout_19.addWidget(self.iniciar_multijugador)
        spacerItem62 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem62)
        self.verticalLayout_18.addLayout(self.horizontalLayout_19)
        spacerItem63 = QtWidgets.QSpacerItem(20, 19, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_18.addItem(spacerItem63)
        self.label_31 = QtWidgets.QLabel(parent=self.multijugador)
        self.label_31.setStyleSheet("font: 87 20pt \"Txt\";\n"
"color: rgb(255, 255, 175);\n"
"background-color: #000000ff;\n"
"\n"
"    ")
        self.label_31.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_18.addWidget(self.label_31)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem64 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem64)
        self.lento = QtWidgets.QPushButton(parent=self.multijugador)
        self.lento.setMinimumSize(QtCore.QSize(130, 0))
        self.lento.setStyleSheet("color: rgb(255, 156, 156);\n"
"border-radius: 5px;\n"
"border: 1px solid white;")
        self.lento.setObjectName("lento")
        self.horizontalLayout_20.addWidget(self.lento)
        spacerItem65 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem65)
        self.medio = QtWidgets.QPushButton(parent=self.multijugador)
        self.medio.setMinimumSize(QtCore.QSize(130, 0))
        self.medio.setStyleSheet("color: rgb(165, 210, 255);\n"
"border-radius: 5px;\n"
"border: 1px solid white;")
        self.medio.setObjectName("medio")
        self.horizontalLayout_20.addWidget(self.medio)
        spacerItem66 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem66)
        self.rapido = QtWidgets.QPushButton(parent=self.multijugador)
        self.rapido.setMinimumSize(QtCore.QSize(130, 0))
        self.rapido.setStyleSheet("color: rgb(188, 255, 187);\n"
"border-radius: 5px;\n"
"border: 1px solid white;")
        self.rapido.setObjectName("rapido")
        self.horizontalLayout_20.addWidget(self.rapido)
        spacerItem67 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem67)
        self.verticalLayout_18.addLayout(self.horizontalLayout_20)
        spacerItem68 = QtWidgets.QSpacerItem(20, 19, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_18.addItem(spacerItem68)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem69 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem69)
        self.menu_s = QtWidgets.QPushButton(parent=self.multijugador)
        self.menu_s.setMinimumSize(QtCore.QSize(200, 0))
        self.menu_s.setMaximumSize(QtCore.QSize(200, 16777215))
        self.menu_s.setStyleSheet("color: rgb(255, 255, 175);\n"
"border-radius: 5px;\n"
"border: 1px solid white;")
        self.menu_s.setObjectName("menu_s")
        self.horizontalLayout_21.addWidget(self.menu_s)
        self.verticalLayout_18.addLayout(self.horizontalLayout_21)
        self.stackedWidget.addWidget(self.multijugador)
        self.ranking = QtWidgets.QWidget()
        self.ranking.setStyleSheet("QWidget {\n"
"    background-color: rgba(0, 0, 0, 100); \n"
"    border-radius:20px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: 87 20pt \"Txt\";\n"
"    background-color: #000000ff;\n"
"    border-radius: 5px;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: black;\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color: rgba(255, 255, 255, 60);  \n"
"    color: rgb(255, 255, 255);\n"
"    gridline-color: rgb(255, 255, 255);\n"
"    font: 15pt \"Txt\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    background-color: rgb(165, 210, 255);\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    font: 15pt \"Txt\";\n"
"}\n"
"\n"
"QTableWidget QTableCornerBurron::section{\n"
"    background-color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(165, 210, 255);\n"
"}")
        self.ranking.setObjectName("ranking")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.ranking)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_29 = QtWidgets.QLabel(parent=self.ranking)
        self.label_29.setMinimumSize(QtCore.QSize(480, 60))
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        self.label_29.setFont(font)
        self.label_29.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.label_29.setStyleSheet("font: 700 35pt \"MS Sans Serif\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: #000000ff;\n"
"")
        self.label_29.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_17.addWidget(self.label_29)
        spacerItem70 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_17.addItem(spacerItem70)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.ranking)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(243)
        self.verticalLayout_17.addWidget(self.tableWidget)
        spacerItem71 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_17.addItem(spacerItem71)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem72 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem72)
        self.actualizar = QtWidgets.QPushButton(parent=self.ranking)
        self.actualizar.setMinimumSize(QtCore.QSize(200, 0))
        self.actualizar.setMaximumSize(QtCore.QSize(200, 16777215))
        self.actualizar.setStyleSheet("color: rgb(188, 255, 187);")
        self.actualizar.setObjectName("actualizar")
        self.horizontalLayout_18.addWidget(self.actualizar)
        spacerItem73 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem73)
        self.menu_r = QtWidgets.QPushButton(parent=self.ranking)
        self.menu_r.setMinimumSize(QtCore.QSize(200, 0))
        self.menu_r.setMaximumSize(QtCore.QSize(200, 16777215))
        self.menu_r.setStyleSheet("color: rgb(255, 156, 156);\n"
"border-radius: 5px;\n"
"border: 1px solid white;")
        self.menu_r.setObjectName("menu_r")
        self.horizontalLayout_18.addWidget(self.menu_r)
        spacerItem74 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem74)
        self.verticalLayout_17.addLayout(self.horizontalLayout_18)
        self.stackedWidget.addWidget(self.ranking)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 11)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 530, 650))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0, stop:0.375 rgba(0, 0, 0, 100), stop:0.835227 rgba(0, 0, 0, 75));\n"
"border-radius: 20px;\n"
"border-radius: 20px;\n"
"\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label.raise_()
        self.label_2.raise_()
        self.frame.raise_()
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_17.setText(_translate("MainWindow", "Bienvenido"))
        self.label_16.setText(_translate("MainWindow", "Modo de juego"))
        self.jugadores1.setText(_translate("MainWindow", "1 Jugador"))
        self.extremo.setText(_translate("MainWindow", "Extremo"))
        self.exit.setText(_translate("MainWindow", "Salir"))
        self.label_13.setText(_translate("MainWindow", "Simon Says"))
        self.label_14.setText(_translate("MainWindow", "Ingresa tu nombre"))
        self.in_nombre1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Txt\'; font-size:20pt; font-weight:87; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.play_5.setText(_translate("MainWindow", "Comenzar"))
        self.menu.setText(_translate("MainWindow", "Menú"))
        self.label_19.setText(_translate("MainWindow", "Simon Extremo"))
        self.label_18.setText(_translate("MainWindow", "Multijugador"))
        self.jugadores2.setText(_translate("MainWindow", "2 Jugadores"))
        self.jugadores3.setText(_translate("MainWindow", "3 Jugadores"))
        self.jugadores4.setText(_translate("MainWindow", "4 Jugadores"))
        self.jugadores5.setText(_translate("MainWindow", "5 Jugadores"))
        self.menu_multi.setText(_translate("MainWindow", "Menú"))
        self.label_6.setText(_translate("MainWindow", "000"))
        self.label_8.setText(_translate("MainWindow", "100"))
        self.label_7.setText(_translate("MainWindow", "Puntuación"))
        self.label_9.setText(_translate("MainWindow", "Mejor \n"
"puntaje"))
        self.label_12.setText(_translate("MainWindow", "Dificultad: "))
        self.lento_2.setText(_translate("MainWindow", "Lento"))
        self.medio_2.setText(_translate("MainWindow", "Medio"))
        self.rapido_2.setText(_translate("MainWindow", "Rápido"))
        self.menu_puntaje.setText(_translate("MainWindow", "Menú"))
        self.label_21.setText(_translate("MainWindow", "2 Jugadores"))
        self.label_20.setText(_translate("MainWindow", "Ingresa los nombres"))
        self.in_nombre.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Txt\'; font-size:20pt; font-weight:87; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.in_nombre_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Txt\'; font-size:20pt; font-weight:87; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.play_4.setText(_translate("MainWindow", "Comenzar"))
        self.menu_2p.setText(_translate("MainWindow", "Menú"))
        self.label_24.setText(_translate("MainWindow", "3 Jugadores"))
        self.label_23.setText(_translate("MainWindow", "Ingresa los nombres"))
        self.in_nombre_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Txt\'; font-size:20pt; font-weight:87; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.in_nombre_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Txt\'; font-size:20pt; font-weight:87; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.in_nombre_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Txt\'; font-size:20pt; font-weight:87; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.play_3.setText(_translate("MainWindow", "Comenzar"))
        self.menu_3p.setText(_translate("MainWindow", "Menú"))
        self.label_27.setText(_translate("MainWindow", "4 Jugadores"))
        self.label_26.setText(_translate("MainWindow", "Ingresa los nombres"))
        self.in_nombre_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Txt\'; font-size:20pt; font-weight:87; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.in_nombre_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Txt\'; font-size:20pt; font-weight:87; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.in_nombre_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Txt\'; font-size:20pt; font-weight:87; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.in_nombre_9.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Txt\'; font-size:20pt; font-weight:87; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.play_2.setText(_translate("MainWindow", "Comenzar"))
        self.menu_4p.setText(_translate("MainWindow", "Menú"))
        self.label_34.setText(_translate("MainWindow", "5 Jugadores"))
        self.label_4.setText(_translate("MainWindow", "Ingresa los nombres"))
        self.in_nombre_10.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Txt\'; font-size:20pt; font-weight:87; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.in_nombre_11.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Txt\'; font-size:20pt; font-weight:87; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.in_nombre_12.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Txt\'; font-size:20pt; font-weight:87; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.in_nombre_13.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Txt\'; font-size:20pt; font-weight:87; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.in_nombre_14.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Txt\'; font-size:20pt; font-weight:87; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.play_1.setText(_translate("MainWindow", "Comenzar"))
        self.menu_5p.setText(_translate("MainWindow", "Menú"))
        self.puntaje_actual.setText(_translate("MainWindow", "000"))
        self.label_30.setText(_translate("MainWindow", "100"))
        self.label_10.setText(_translate("MainWindow", "Puntuación"))
        self.label_32.setText(_translate("MainWindow", "Mejor \n"
"puntaje"))
        self.label_31.setText(_translate("MainWindow", "Dificultad: "))
        self.lento.setText(_translate("MainWindow", "Lento"))
        self.medio.setText(_translate("MainWindow", "Medio"))
        self.rapido.setText(_translate("MainWindow", "Rápido"))
        self.menu_s.setText(_translate("MainWindow", "Menú"))
        self.label_29.setText(_translate("MainWindow", "Ranking"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Puntaje"))
        self.actualizar.setText(_translate("MainWindow", "Actualizar"))
        self.menu_r.setText(_translate("MainWindow", "Menú"))
