# Form implementation generated from reading ui file '/Users/j0z3ph/Repos/2024-2/PAM/P8/ventana.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 100)
        MainWindow.setMinimumSize(QtCore.QSize(300, 100))
        MainWindow.setMaximumSize(QtCore.QSize(300, 100))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 58, 16))
        self.label.setObjectName("label")
        self.editNombre = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.editNombre.setGeometry(QtCore.QRect(90, 20, 181, 22))
        self.editNombre.setMaxLength(20)
        self.editNombre.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.editNombre.setObjectName("editNombre")
        self.btnAceptar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAceptar.setGeometry(QtCore.QRect(190, 55, 80, 31))
        self.btnAceptar.setObjectName("btnAceptar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mi Ventana"))
        self.label.setText(_translate("MainWindow", "Nombre"))
        self.editNombre.setPlaceholderText(_translate("MainWindow", "Pon tu nombre aqui"))
        self.btnAceptar.setText(_translate("MainWindow", "Aceptar"))
