# Form implementation generated from reading ui file 'e:\Programacion\Programacion_Avanzada_2MV7\Practica7\Equipo_Buena_Onda_Codigos\buscar_usuario.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(271, 100)
        Dialog.setStyleSheet("*{\n"
"    font: 11pt \"Tempus Sans ITC\";\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"    color: #fff;\n"
"}\n"
"\n"
"#Dialog{\n"
"    background-color: #1f232a;\n"
"}\n"
"\n"
"QPushButton{\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-radius:10px;\n"
"background-color: rgb(23,139,216);\n"
"}\n"
"\n"
"QLineEdit{\n"
"border-radius:10px;\n"
"border: 2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"border: 2px solid rgb(23,139,216);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255,255,255);\n"
"border: 2px solid rgb(91,220,252);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.buscar_usuario = QtWidgets.QLineEdit(parent=Dialog)
        self.buscar_usuario.setObjectName("buscar_usuario")
        self.verticalLayout.addWidget(self.buscar_usuario)
        self.boton_buscar = QtWidgets.QPushButton(parent=Dialog)
        self.boton_buscar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.boton_buscar.setObjectName("boton_buscar")
        self.verticalLayout.addWidget(self.boton_buscar, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "INGRESA EL NOMBRE"))
        self.boton_buscar.setText(_translate("Dialog", "ACEPTAR"))
